Disable Security/YAMLLoad cop for Ruby 2.0.x
NoMethodError: undefined method `safe_load' for Psych:Module
  /home/travis/build/danger/danger/lib/danger/commands/init.rb:180:in `uses_travis'
  /home/travis/build/danger/danger/lib/danger/commands/init.rb:154:in `setup_danger_ci'
  /home/travis/build/danger/danger/lib/danger/commands/init.rb:38:in `run'
  /home/travis/build/danger/danger/bundle/ruby/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /home/travis/build/danger/danger/bin/danger:5:in `<top (required)>'
  /home/travis/build/danger/danger/bundle/ruby/2.0.0/bin/danger:23:in `load'
  /home/travis/build/danger/danger/bundle/ruby/2.0.0/bin/danger:23:in `<top (required)>'